main: jp.jyn.byebyewither.ByeByeWither
name: "${project.artifactId}"
version: "${project.version}"
website: https://jyn.jp/bukkit_byebyewither/
author: '@HimaJyun'

commands:
   byebyewither:
      description: '/byebyewither reload - Reload the plugin'
   bbw:
      description: 'Alias of "/bbw"'

permissions:
  byebyewither.*:
    byebyewither.allowdragon: true
    byebyewither.reload: true
  byebyewither.allowdragon:
    default: op
  byebyewither.reload:
    default: op