name: "ByeByeWither"
version: @version@
main: "jp.jyn.byebyewither.ByeByeWither"
author: "HimaJyun( https://jyn.jp/ ) and GiganticMinecraft ( https://www.seichi.network/ )"
api-version: 1.18

commands:
    byebyewither:
        description: '/byebyewither reload - Reload the plugin'
        aliases: bbw

permissions:
    byebyewither.*:
        byebyewither.bypass-dragon: true
        byebyewither.reload: true
    byebyewither.bypass-dragon:
        default: op
    byebyewither.reload:
        default: op
